<?php
session_start();
if(!isset($_SESSION['Email']))
{
header('location:http://localhost/project1/front.php');
}
$v=$_SESSION['Email'];
$w=$_SESSION['Password'];
$review=$_POST['review'];
$con=mysqli_connect('localhost','root');
$b=mysqli_select_db($con,'healthcare');
$q="select * from customer where Email='$v' && Password='$w'";
$i=mysqli_query($con,$q);
$num=mysqli_num_rows($i);
for($m=1;$m<=$num;$m++)
{
    $row=mysqli_fetch_array($i);
$first_name=$row['First_Name'];
    $last_name=$row['Last_Name'];
}
$wp="insert into review(Name,Last_Name,Suggestion) values ('$first_name','$last_name','$review')";
 $i=mysqli_query($con,$wp);
if($i==1)
{
    header('location:http://localhost/project1/review.php');
}
else
{
    header('location:http://localhost/project1/review.php');
}
mysqli_close($con);
?>